data:
  train_val_test_ratio: [0.6, 0.2, 0.2]
  dataset: 
    name: BoWDataset
    # load_path: "models/preprocessing/bow_dataset"
    save_path: "models/preprocessing/bow_dataset"
    data_path: "data/filtered.tsv"
    nltk_args:
      num_workers: 4
    size: 1000
    minimum_freq: 100
    verbose: true
  dataloader:
    batch_size: 16
    num_workers: 1
model:
  name: LogisticRegression
  input_dim: 1000
training:
  optimizer_args:
    name: torch.optim.Adam
    lr: 0.1
  trainer_args:
    max_epochs: 5
    default_root_dir: "models/toxicity_log_regr"

