data:
  train_val_test_ratio: [0.6, 0.2, 0.2]
  dataset: 
    name: BoWDataset
    load_path: "models/preprocessing/bow_dataset"
#     save_path: "models/preprocessing/bow_dataset"
    data_path: "data/filtered.tsv"
    nltk_args:
      num_workers: 15
    size: 4000
    minimum_freq: 100
    verbose: true
  dataloader:
    batch_size: 64
    num_workers: 7
model:
  name: LogisticRegression
  input_dim: 4000
training:
  optimizer_args:
    name: torch.optim.Adam
#     lr: 0.1
  trainer_args:
    max_epochs: 3
    default_root_dir: "models/toxicity_log_regr"

